export function resetTransientState(target) {
  target.companion = null;
  target.noticeQueue = [];
  target.arenaRound = null;
  target.pendingImport = null;
  target.roomFriend = null;
  target.decorateSlot = null;
  target.decoratePage = 0;
  target.decorateItem = null;
  target.mansionPage = 0;
  target.creatorPage = 0;
  target.typingPage = 0;
  target.learningPage = 0;
  target.friendLineIndex = {};
  target.arenaCup = null;
  target.arenaCreature = null;
  target.arenaPickPage = 0;
  target.achievementPage = 0;
  target.giftFriend = null;
  target.giftPage = 0;
  target.wardrobeCategory = "clothing";
  target.wardrobePage = 0;
  target.displayCategory = "dinosaurs";
  target.displayPage = 0;
  target.deferredToast = null;
  target.toastShownAt = 0;
  target.walkPath = [];
  target.walkDestination = null;
  target.nearDoor = null;
  target.nearFriend = null;
  target.activity = null;
  target.modalOpen = false;
  target.page = 0;
  target.category = "friends";
  target.memoryPage = 0;
  target.shopCategory = "clothing";
  target.shopPage = 0;
  target.walkOverview = false;
  target.editing = false;
  target.draft = null;
  target.newSlot = null;
  target.walkKeys?.clear();
  return target;
}
